### ISSUE TITLE
Extract libp2p code into a separate module

### ISSUE THREAD

**Issue by sethhrbek** [sarcophagus-org/sarcophagus-v2-app#160]
Remove libp2p logic from main application state and encapsulate in a separate part of the project. Components requiring data loaded via libp2p should call out to this module to retrieve data (like the discovered archaeologists).

**Comment by gh-23378** [comment]
Low priority edge case --

During the discovery interval (the interval at which the browser node detects the set of discovered archaeologists), nodes may possibly go online/offline.

If nodes enter/leave the network after the archaeologist UX screen is loaded, we need to inform the user that their archaeologist list has changed.

One way we were considering doing this-
On an interval, detect if the arch set in global state has changed (including the isOnline field). if the archs state has changed, then show the user a "refresh" button which indicates the arch list needs to be refreshed. Clicking this button will refresh the arch table with the updated state.

We will need to think through how this plays nice with archs that have already been selected & any filters applied in the UX.
