### ISSUE TITLE
Resurrection Time has an error but not displayed on Summary Screen (UPDATED)

### ISSUE THREAD

**Issue by sethhrbek** [sarcophagus-org/sarcophagus-v2-app#242]
~From the image below. The user cannot create the sarcophagus because the resurrections date is in the past. We should show a red ! as an error on the Summary page.~ This is fixed in [#238](https://github.com/sarcophagus-org/sarcophagus-v2-app/pull/238). Comments below can still be looked at.

And also could add `filterTime={filterInvalidTime}` see Rewrap.tsx so user cannot select past time in the past, and filter for times greater than archeaolgist allow.

![Image](https://user-images.githubusercontent.com/99622829/201979885-23a9e439-bfd9-40b0-a4eb-cfd162a3e825.png)

**Comment by solidoracle** [comment]
Confirm that if a date in the past is selected an error comes out in the summary page and you are unable to create the sarco

![Screenshot 2022-11-24 at 10 59 10](https://user-images.githubusercontent.com/105349716/203754592-2189117b-151c-4a82-85ed-ce2d020eeed8.png)
