### ISSUE TITLE
Show alert when leaving "Create Sarcophagus"

### ISSUE THREAD

**Issue by sethhrbek** [sarcophagus-org/sarcophagus-v2-app#248]
If a user attempts to leave the page, either by refreshing the page or by clicking on a header link, when in the process of the final step of "create sarcophagus" (the one with the steps on the side to create the TX):

1. They should be notified that they will lose all their progress. This  can be done via a modal alert box. See if we already have a modal setup (we may) that can be used for this. Otherwise, create a basic modal using Chakra.

If we don't have a modal and you need an example design, you can use the "hidden archs" modal in the figma as a template:

![Image](https://user-images.githubusercontent.com/43755993/203814529-6242ce73-3ce8-4a0b-ad52-8c93406c65c1.png)

2. The modal should have a "confirm" or "cancel" button. If the user confirms, then they should continue to whatever page they were going to and the state should be cleared. To clear the state:
a. Use the `clearSarcophagusState` method in the `useClearSarcophagusState` hook
b. Call `dispatch(goToStep(Step.NameSarcophagus))` to reset to the first step.

There should be a way to do this with React to detect when the component is unloading from the window. At that point the alert modal should show.

**Comment by solidoracle** [comment]
Doing some research and it seems like to avoid scamming, chrome have decided to remove the ability to set a custom message in the onbeforeunload dialog that is fired before the refresh. Trying to understand if this is the case as well to set custom modals

https://bugs.chromium.org/p/chromium/issues/detail?id=587940

This is what is what seems possible:
<img width="255" alt="Screenshot 2022-11-25 at 16 08 02" src="https://user-images.githubusercontent.com/105349716/204012730-c704c726-8fb7-401c-abe4-36d67ac34f94.png">

**Comment by sethhrbek** [comment]
@solidoracle -- thanks for looking into that -- this is 100% sufficient solution for the refresh. For the user browsing to a different page on the app, we should use the modal if possible.

**Comment by solidoracle** [comment]
As of today, React Router v6 doesn't ship with support for preventing transitions: https://github.com/remix-run/react-router/issues/8139#issuecomment-954425560

I've implemented a workaround with a custom hook that doesn't include a custom modal:
![Screenshot 2022-11-28 at 08 53 14](https://user-images.githubusercontent.com/105349716/204223062-08f9ffc1-0605-4627-b283-ec495b80d51e.png)

Looking into applying a custom modal next

**Comment by solidoracle** [comment]
Completed functionality and styling of modal:

![Screenshot 2022-11-29 at 10 13 46](https://user-images.githubusercontent.com/105349716/204487970-5eaf0e8c-78a2-4f58-a529-c1aa87ebf214.png)
