### ISSUE TITLE
UI bugs

### ISSUE THREAD

**Issue by gh-23378** [sarcophagus-org/sarcophagus-v2-app#263]
- digging and protocol fees shouldn't look clickable on detail page
![Image](https://user-images.githubusercontent.com/8015883/205397067-ca571903-2b4e-4df5-8c55-e67d9cf37920.png)
- buttons become disabled (but still look clickable) after executing rewrap or bury, should revert to the default state of detail page with no action
![Image](https://user-images.githubusercontent.com/8015883/205397158-5b638d00-9095-43e5-bf9c-d39e42e857ba.png)
- clicking details in breadcrumbs takes user back to dashboard table
- empty actions list should not be underlined
![Image](https://user-images.githubusercontent.com/8015883/205397330-163170b0-a95c-4704-8940-9c7435b903b4.png)
- date selector on step 1 should gray out times before current time
![Image](https://user-images.githubusercontent.com/8015883/205397535-1f90f169-b31a-483f-89d9-dfa7d1cd21d8.png)
- hide triple dot menu in upper right
- if user clicks edit button on summary page then clicks back, they're not taken back to the summary page

**Comment by gh-23378** [comment]
Burying a sarcophagus does not update its state immediately in the detail page, so the user is allowed to try to bury an already buried sarcophagus

**Comment by gh-23378** [comment]
Claim tab should not show Active sarcophagi - check for resurrected state

**Comment by knoll3** [comment]
> if user clicks edit button on summary page then clicks back, they're not taken back to the summary page
 
The create sarcophagus process is a single page so there is no history being tracked as the user navigates the creation process. It is possible to intercept a click on the back button but I don't think this is a good idea.
