### ISSUE TITLE
Disconnected from Bundlr toast appears more than once

### ISSUE THREAD

**Issue by knoll3** [sarcophagus-org/sarcophagus-v2-app#285]
> Upon clicking the address in the top right, then disconnecting the wallet, “Disconnected from Bundlr node” toast appears in the bottom right of the screen then goes away for a moment and comes back unless you close the page.

This does not happen consistently but it does happen. Also it's not likely a loop but multiple toasts being dispatched when only one should be dispatched.

Documented in Notion. 
https://www.notion.so/sarcopahgus/Sarcophagus-Embalmer-V2-Issues-and-Feedback-516b8ddcf4f548de8d6bfc43ccd7918a#f6d4080f6474481e849aad51d7387bf6

**Comment by sethhrbek** [comment]
@knoll3 -- if the solution to this doesn't manifest quickly, would ice this one as its not causing any harm.
