### ISSUE TITLE
Sarcophagus Admin Dashboard

### ISSUE THREAD

**Issue by sethhrbek** [sarcophagus-org/sarcophagus-v2-app#355]
Create basic page that displays the number of sarcophagi that have been created using events. Research should be done on how many RPC calls will be made to retrieve the events.

Note:
There isn't a getter for all sarcophagi on the contracts. We can use events to query these -- an example of how to query these is below:

```
  useEffect(() => {
    const fetchEvents = async () => {
      const contract = EmbalmerFacet__factory.connect(networkConfig.diamondDeployAddress, provider);
      const events = await contract.queryFilter('CreateSarcophagus');
      console.log(events);
    };

    fetchEvents()
      .catch((error) => {
        console.log('error', error);
      });
  }, []);
```

There's going to be a lot of sarcophagi (over 900+), so we should do some caching of these IDs as well as calls to `getSarcophagus`. Any Sarcophagi that doesn't have an active status should probably be cached in local storage.

**Comment by knoll3** [comment]
Changed the task description to only show the sarco count instead of a table of sarcos based on our conversation during today's standup.
