### ISSUE TITLE
P2P node connection heartbeat

### ISSUE THREAD

**Issue by sethhrbek** [sarcophagus-org/sarcophagus-v2-app#82]
Note: add a global timestamp for when the first discovery process starts (basically when the browser node starts up). We will use this timstamp to determine if enough time has elapsed in order to show the arch multi-select table.

Possible implemention -- discovery happens every 10 or so seconds. It might be possible to use `discoveredArchs` to track when they were last 'pinged', and assume they are offline if too much time passes without such a 'ping'.

---

We will need to think through the workflow where this error is thrown.

We will probably need a way to monitor these connections during this communication workflow (maybe on an interval in it's own routine) and communicate specifically which archaeologist has dropped so the webapp can either retry or inform the user that one of the archaeologists is unavailable. Then we will need to scope out what the "replace archaeologist" workflow looks like.

As an aside -- do you know what would make this archConnection null/undefined? For example, if the browser connects to an archaeologist, but then the archaeologist goes offline, will this connection object still be defined?
I'm hopeful it would, but if it doesn't, we may need some extra logic on the "liveness" interval check to see if the comms connection is healthy.

**Comment by DarksightKellar** [comment]
Implemented in #83
