### ISSUE TITLE
useLibp2p refactor

### ISSUE THREAD

**Issue by sethhrbek** [sarcophagus-org/sarcophagus-v2-app#87]
https://github.com/sarcophagus-org/sarcophagus-v2-app/pull/86

Refactor useLibp2p into 2 hooks, one of which is responsible for booting up the libp2p node.

Move the public key stream handler into a different location so it has access to the state in needs access to, specifically right before the call to dialArchaeologists

Knock off a couple TODOs in the useLibp2p hook.

**Comment by DarksightKellar** [comment]
Is this issue good to be closed?

**Comment by sethhrbek** [comment]
@DarksightKellar -- yes, good call! Closing now.
